name: ${name}
description: ${description}
authors:
  - srnyx
website: https://srnyx.com

main: ${group}.pl3xmap.supervanish.Pl3xMapSuperVanish
version: ${version}
api-version: 1.13

depend:
  - Pl3xMap
  - SuperVanish
