name: ${name}
description: ${description}
authors:
  - srnyx
website: https://srnyx.com

main: ${mainPackage}.Pl3xMapSuperVanish
version: ${version}
api-version: 1.19

depend:
  - Pl3xMap

softdepend:
  - SuperVanish
  - PremiumVanish
